### ISSUE TITLE
Converted volume is missing the last block

### ISSUE THREAD

**Issue by boredzo** [boredzo/impluse-hfs#49]
An HFS+ volume is supposed to end with the alternate volume header followed by 0x200 unused bytes. Together, these occupy the last 0x400 bytes of the volume (even if that doesn't start on an allocation block boundary).

Currently, impluse's output from converting a bare volume is 0x200 bytes too short, and ends immediately with the alternate volume header. The last 0x200 bytes isn't getting copied or created.

**Comment by boredzo** [comment]
This broke with daed9e91dff24386652abdabd174fbec5b200878.

I'd forgotten what that `ftruncate` was for—it was for creating those last 0x200 bytes.

I'm not sure how credible the commit's claim is, that calling `ftruncate` in output volume creation broke copying other partitions. I'm fairly sure that happens _after_ that point. Seems like I could put it back, and fix conversion of bare volumes, without breaking partitions.

(Side note: Partitioned images seem to _gain_ an extra 0x200 bytes from conversion. I'm not sure how or where from, or whether that's related to this.)

**Comment by GeckoGB** [comment]
Is it possible, as a temporary workaround, to manually add the missing data at the end of the generated image?

0x200 unused byte: easy

alternate volume header: if i understand right, it is a copy of the volume header located 1024 bytes after the beginning of the HFS partition, right? So i should only have to find the beginning of HFS partition in the disk image and copy 0x200 bytes starting at 0x400 offset from the beginning?

**Comment by boredzo** [comment]
The alternate volume header is already getting put into the right place, so you should only need to append another 0x200 of zero bytes.

[Edit: These instructions only work on bare-volume images. They won't work on partitioned images; you might be inserting the bytes after some other partition. The task is to insert them at the end of the HFS partition, but inserting 0x200 bytes anywhere in a partitioned image is tricky.]

[If you mount the partitioned image, then copy the HFS volume to a new bare-volume image, then] That can be done with [truncate](https://github.com/boredzo/truncate):

```
ls -dl output.img
(add 512 to the size of the file)
truncate $NEWSIZE output.img
```

or with dd:

```
dd if=/dev/zero bs=512 count=1 oseek=$OLDSIZE of=output.img
```

>if i understand right, it is a copy of the volume header located 1024 bytes after the beginning of the HFS partition, right? 

It is a copy of the volume header, but it's 1024 bytes before the end. The last two 512-byte blocks should be the alternate volume header and an unused/empty block.

(Notably, this is independent of allocation-block boundaries. The last 1K may be two allocation blocks, or one, or a non-initial part of a larger allocation block.)

impluse is writing the alternate volume header where it's supposed to be, but not appending 512 bytes after it. That's why the file ends up 512 bytes too short, and why fsck complains about not finding the alternate volume header.

**Comment by GeckoGB** [comment]
> but it's 1024 bytes before the end
I was talking about the position of the "main" volume header, from the beginning. But yes, i saw that the location of alternate volume header is at 1024 bytes from the end.
And yes, both are obvisouly related to the position of the HFS+ partition inside the whole volume image.

But since you have already fixed that too, i don't have to worry about that 😉

5 ⭐️⭐️⭐️⭐️⭐️ support 👍
